version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-volume:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - node-network

  api:
    build:
      context: ./api
    container_name: api
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s node index.js
    environment:
      - PORT=3000
      - CONNECTION_STRING=mysql://root:root@db:3306/nodedb
    networks:
      - node-network
    volumes:
      - /app
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - '8080:80'
    networks:
      - node-network
    depends_on:
      - api

volumes:
  db-volume:

networks:
  node-network:
    driver: bridge
